import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar";
import { ThemeProvider } from "@/components/theme-provider";
import { Toaster } from "@/components/ui/toaster";
import { Modal } from "@/components/modals/modal";
import AddWineModal from "@/components/modals/add-wine-modal";
import getCurrentUser from "@/actions/getCurrentUser";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // const router = useRouter();
  const currentUser = await getCurrentUser();

  // if (!currentUser) {
  //   router.push("/login");
  // }
  // console.log(currentUser ? currentUser : 'No current user')

  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <AddWineModal />
          {currentUser ? <Navbar /> : ''}
          {children}
          <Toaster />
        </ThemeProvider>
      </body>
    </html>
  );
}
